### ISSUE TITLE
FileNotFoundException on (start-repl)

### ISSUE THREAD

**Issue by kgxsz** [adzerk-oss/boot-cljs-repl#17]
Hi,

I'm trying to get a browser repl going with:
```
boot -- serve -k -d target -- watch -- speak -- reload -- cljs-repl -- cljs -O none
```

But I get this: 
```
java.io.FileNotFoundException: Could not locate cljs/env__init.class or cljs/env.clj on classpath: , compiling:(cemerick/piggieback.clj:1:1)
```

I've tried adding the following dependencies, but they don't seem to help:
```
[com.cemerick/piggieback "0.2.1"]
[org.clojure/tools.nrepl "0.2.10"]
```

Here is my `build.boot` file:
```
(set-env!
  :source-paths   #{"src"}
  :resource-paths #{"resources"}
  :dependencies '[[org.clojure/clojure "1.6.0"]
                  [org.clojure/clojurescript "0.0-3308"]
                  [adzerk/boot-cljs "0.0-3269-2"]
                  [adzerk/boot-cljs-repl "0.1.9"]
                  [adzerk/boot-reload "0.2.6"]
                  [pandeiro/boot-http "0.6.2"]
                  [com.cemerick/piggieback "0.2.1"]
                  [org.clojure/tools.nrepl "0.2.10"]
                  [org.omcljs/om "0.8.8"]
                  [prismatic/om-tools "0.3.10" :exclude [prismatic/schema
                                                         prismatic/plumbing]]
                  [prismatic/schema "0.4.2"]
                  [prismatic/plumbing "0.4.3"]
                  [prismatic/dommy "1.0.0"]])

(require
  '[adzerk.boot-cljs :refer [cljs]]
  '[adzerk.boot-reload :refer [reload]]
  '[adzerk.boot-cljs-repl :refer [cljs-repl start-repl]]
  '[pandeiro.boot-http :refer [serve]])
```

Any clues on what I'm doing wrong?

Thank you!

**Comment by alxlit** [comment]
It needs updating ([note](https://github.com/adzerk-oss/boot-cljs/commit/9e959a0a17f7ccf813e2d7d5f6c06c7948b12e71)), downgrading boot-cljs to 0.0-3269-2 and clojurescript 0.0-3269 works for me.

**Comment by kgxsz** [comment]
Unfortunately I still get those errors with those versions :(

**Comment by tomjakubowski** [comment]
Are you using clojure 1.7.0-RC2?

**Comment by kgxsz** [comment]
Okay, so here is my `build.boot`:

```
(set-env!
  :source-paths   #{"src"}
  :resource-paths #{"resources"}
  :dependencies '[[org.clojure/clojure "1.7.0-RC2"]
                  [org.clojure/clojurescript "0.0-3269"]
                  [adzerk/boot-cljs "0.0-3269-2"]
                  [adzerk/boot-cljs-repl "0.1.10-SNAPSHOT"]
                  [adzerk/boot-reload "0.3.0"]
                  [pandeiro/boot-http "0.6.2"]
                  [org.martinklepsch/boot-garden "1.2.5-4"]
                  [org.omcljs/om "0.8.8"]
                  [prismatic/om-tools "0.3.10" :exclude [prismatic/schema
                                                         prismatic/plumbing]]
                  [prismatic/schema "0.4.2"]
                  [prismatic/plumbing "0.4.3"]
                  [prismatic/dommy "1.0.0"]
                  [garden "1.2.5"]])

(require
  '[adzerk.boot-cljs :refer [cljs]]
  '[adzerk.boot-reload :refer [reload]]
  '[adzerk.boot-cljs-repl :refer [cljs-repl start-repl]]
  '[pandeiro.boot-http :refer [serve]])
```

When I run `boot -- serve -d target/ -k -- watch -- speak -- reload -- cljs -O none` I'm all good, but then I try `boot -- serve -d target/ -k -- watch -- speak -- reload -- cljs-repl -- cljs -O none` and I get:

```
clojure.lang.Compiler$CompilerException: java.io.FileNotFoundException: Could not locate cljs/env__init.class or cljs/env.clj on classpath: , compiling:(cemerick/piggieback.clj:1:1)
          java.io.FileNotFoundException: Could not locate cljs/env__init.class or cljs/env.clj on classpath:
```

Curiously, in the output I see `Adding Clojure 1.7.0-RC1 for Cljs compiler`, which seems strange to me given that I've specified RC2.  I also nuked my `~/.m2 ` directory to be sure.

So not sure why I'm getting this. Any ideas would be very much appreciated, and thank you for your help so far.

**Comment by Deraen** [comment]
@kgxsz Try with latest `boot-cljs` (0.0-3269-4 or 0.0-3308-0). It doesn't do magic with Clojure versions and should give proper messages if you don't have clojure 1.7 properly set up.

**Comment by kgxsz** [comment]
Okay, the only way I can get it working is with the following combination of dependencies:

```
...
  :dependencies '[[org.clojure/clojure "1.7.0-RC2"]
                  [org.clojure/clojurescript "0.0-3123"]
                  [adzerk/boot-cljs "0.0-3308-0"]
                  [adzerk/boot-cljs-repl "0.1.10-SNAPSHOT"]
                  [adzerk/boot-reload "0.3.0"]
                  [pandeiro/boot-http "0.6.2"]
                  [org.martinklepsch/boot-garden "1.2.5-4"]
                  [org.omcljs/om "0.8.8"]
                  [prismatic/om-tools "0.3.10" :exclude [prismatic/schema
                                                         prismatic/plumbing]]
                  [prismatic/schema "0.4.2"]
                  [prismatic/plumbing "0.4.3"]
                  [prismatic/dommy "1.0.0"]
                  [garden "1.2.5"]])

...
```
If I up clojurescript to 3308 then it fails.

Aside from getting the following warnings, it seems to work fine:

```
WARNING: CLJS version older than boot-cljs: 0.0-3123
temp-dir! was deprecated, please use tmp-dir! instead
tmppath was deprecated, please use tmp-path instead
tmpfile was deprecated, please use tmp-file instead
```

Any ideas why I can't up the version of clojurescript to 3308 with the latest version of boot-cljs-repl?

Cheers

**Comment by kul** [comment]
I got the exact same error for `boot-cljs` itself so i guess it not specific to repl. Make sure boot has same version of clojure both for itself i.e. boot.properties and in the project.

**Comment by pkobrien** [comment]
The latest version of `[adzerk/boot-cljs-repl "0.1.10-SNAPSHOT"]` has been updated to the newest versions of all dependencies and should solve these problems. In your build.boot files you should *not* need to depend on piggieback, nrepl, or weasel. Please test this version and let us know if it works for you or not.

**Comment by unrealhoang** [comment]
@pkobrien 
```
  :dependencies '[[adzerk/boot-cljs "0.0-3308-0" :scope "test"]
                  [adzerk/boot-cljs-repl "0.1.10-SNAPSHOT"   :scope "test"]
                  [adzerk/boot-reload    "0.2.6"      :scope "test"]
                  [pandeiro/boot-http    "0.3.0"      :scope "test"]
                  [org.clojure/clojure "1.7.0"]
                  [org.clojure/clojurescript "0.0-3308"] ])
```

I've just tried with this set of dependencies, and still have the same error. It seems the error comes from clojurescript itself.
I set the `clojurescript` dependency to 3123 according to @kgxsz and it works.

**Comment by pkobrien** [comment]
@unrealhoang Can you try using `[adzerk/boot-reload "0.3.1" :scope "test"]` and `[pandeiro/boot-http "0.6.3-SNAPSHOT" :scope "test"]`?

**Comment by kgxsz** [comment]
Thanks for the update @pkobrien and @kul.

Here is what I did:

- Updated my deps to what you can see below.
- Nuked my `~/.m2/repositories` directory because I'm OCD.
- Edited my `~/.boot/cache/boot.properties` and made it such that `BOOT_CLOJURE_VERSION=1.7.0-RC2`.

Then ran my build and it worked!

But I now have two gripes associated with this solution:

- When I run `boot -u` my boot clojure version goes back to 1.6.0 and my build is broken again, am I editing the wrong config file?
- I also get some warnings I've never seen, but I'm guessing are minor: 

    ```
    WARNING: org.clojure/tools.nrepl version null is older than required 0.2.10
    Connection is null
    ```

@unrealhoang, for reference here are the combinations of deps that work:

```
(set-env!
  :source-paths   #{"src"}
  :resource-paths #{"resources"}
  :dependencies '[[org.clojure/clojure "1.7.0-RC2"]
                  [org.clojure/clojurescript "0.0-3308"]
                  [adzerk/boot-cljs "0.0-3308-0"]
                  [adzerk/boot-cljs-repl "0.1.10-SNAPSHOT"]
                  [adzerk/boot-reload "0.3.1"]
                  [pandeiro/boot-http "0.6.3-SNAPSHOT"]
                  [org.martinklepsch/boot-garden "1.2.5-4"]
                  [org.omcljs/om "0.8.8"]
                  [cljsjs/d3 "3.5.5-3"]
                  [prismatic/om-tools "0.3.10" :exclude [prismatic/schema
                                                         prismatic/plumbing]]
                  [prismatic/schema "0.4.2"]
                  [prismatic/plumbing "0.4.3"]
                  [prismatic/dommy "1.0.0"]
                  [garden "1.2.5"]])
```

**Comment by pkobrien** [comment]
@kgxsz I'm glad it's working for you. Note that Clojure 1.7.0 has been released so you don't need "RC2" anymore, unless you have some reason not to use the full release.

Yes, if you run `boot -u` without also specifying an environment variable of BOOT_CLOJURE_VERSION=1.7.0 it will revert to its built-in version, 1.6.0. So you can either put this environment variable in your system, use the env variable on the command-line, or create a local boot.properties file for your project.

The nrepl warning and null connection messages are harmless, but I'd like to see them go away soon.

**Comment by kgxsz** [comment]
Brilliant! Thanks for all your help. Very much appreciated.

**Comment by unrealhoang** [comment]
Thanks @kgxsz @pkobrien for awesome help, I got it working using BOOT_CLOJURE_VERSION=1.7.0.

**Comment by pkobrien** [comment]
Excellent! Glad to see that this is working for everyone. :+1:
